version = 1

[[annotations]]
path = ["**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Jonas Hagmar"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["CODE_OF_CONDUCT.md"]
precedence = "override"
SPDX-FileCopyrightText = "Contributor Covenant contributors"
SPDX-License-Identifier = "CC-BY-4.0"
